

services:
  mongo:
    image: mongo
    container_name: breezy-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  post:
    build: ./backend/apps/post
    container_name: breezy-post
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/post
    volumes:
      - ./backend/apps/post:/app
      - /app/node_modules

    restart: always

volumes:
  mongo-data:
