services:
  breezy-mongo:
    image: mongo:6
    container_name: breezy-mongo
    restart: always
    ports:
      - "27027:27017"
    volumes:
      - mongo-data:/data/db

  followers:
    build:
      context: ./apps/followers
    container_name: followers
    environment:
      - MONGO_URI=mongodb://breezy-mongo:27017/breezy
    depends_on:
      - breezy-mongo
    ports:
      - "4002:4002"

  publicprofile:
    build:
      context: ./apps/publicprofile
      dockerfile: Dockerfile
    container_name: publicprofile
    environment:
      - MONGO_URI=mongodb://breezy-mongo:27017/breezy
    depends_on:
      - breezy-mongo
    ports:
      - "4001:4001"

  userprofile:
    build:
      context: ./apps/userprofile
      dockerfile: Dockerfile
    container_name: userprofile
    environment:
      - MONGO_URI=mongodb://breezy-mongo:27017/breezy
      - JWT_SECRET=super_secret_token_breezy
    depends_on:
      - breezy-mongo
    ports:
      - "4003:4003"

  useraccount:
    build:
      context: ./apps/useraccount
      dockerfile: Dockerfile
    container_name: useraccount
    environment:
      - MONGO_URI=mongodb://breezy-mongo:27017/breezy
    depends_on:
      - breezy-mongo
    ports:
      - "4004:4004"
    volumes:
      - ./libs:/app/libs

  authentification:
    build:
      context: ./apps/authentification
      dockerfile: Dockerfile
    container_name: authentification
    environment:
      - MONGO_URI=mongodb://breezy-mongo:27017/breezy
      - JWT_SECRET=super_secret_token_breezy
    depends_on:
      - breezy-mongo
    ports:
      - "4005:4005"
  
  post:
    build:
      context: ./apps/post
      dockerfile: Dockerfile
    container_name: post
    environment:
      - MONGO_URI=mongodb://breezy-mongo:27017/breezy
    depends_on:
      - breezy-mongo
    ports:
      - "4006:4006"

  interaction:
    build:
      context: ./apps/interaction
      dockerfile: Dockerfile
    container_name: interaction
    environment:
      - MONGO_URI=mongodb://breezy-mongo:27017/breezy
    depends_on:
      - breezy-mongo
    ports:
      - "4007:4007"

  feed:
    build:
      context: ./apps/feed
      dockerfile: Dockerfile
    container_name: feed
    environment:
      - MONGO_URI=mongodb://breezy-mongo:27017/breezy
    depends_on:
      - breezy-mongo
    ports:
      - "4008:4008"

  nginx:
    image: nginx:alpine
    container_name: breezy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - followers
      - publicprofile
      - userprofile
      - useraccount
      - authentification
      - post

  gateway:
    build:
      context: ./apps/gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "4000:4000"
    depends_on:
      - followers
      - publicprofile
      - userprofile
      - useraccount
      - authentification
      - post
      - interaction
      - feed

volumes:
  mongo-data: