version: '3.8'

services:
  mongo:
    image: mongo
    container_name: breezy-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  post:
    build: ./apps/post
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/post
    volumes:
      - ./apps/post:/app
      - /app/node_modules
    restart: always

  useraccount:
    build: ./apps/userAccount
    ports:
      - "5051:5050"
    env_file:
      - ./apps/userAccount/.env
    depends_on:
      - mongo
    volumes:
      - ./apps/userAccount:/app
      - /app/node_modules
    restart: always

  authentification:
    build: ./apps/authentification
    ports:
      - "4000:4000"
    env_file:
      - ./apps/authentification/.env
    depends_on:
      - mongo
    volumes:
      - ./apps/authentification:/app
      - /app/node_modules
    restart: always

  publicprofile:
    build: ./apps/publicProfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/publicprofile
    volumes:
      - ./apps/publicProfile:/app
      - /app/node_modules
    restart: always

  userprofile:
    build: ./apps/userProfile
    ports:
      - "4002:4002"
    env_file:
      - ./apps/userProfile/.env
    depends_on:
      - mongo
    volumes:
      - ./apps/userProfile:/app
      - /app/node_modules
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../frontend:/usr/share/nginx/html
    depends_on:
      - userprofile
      - publicprofile
      - useraccount
      - authentification
    restart: always

volumes:
  mongo-data: