services:
  mongo:
    image: mongo:6
    container_name: breezy-mongo
    restart: always
    ports:
      - "27027:27017"
    volumes:
      - mongo-data:/data/db

  followers:
    build: ./apps/followers
    container_name: followers
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy
    depends_on:
      - mongo
    ports:
      - "4002:4002"

  publicprofile:
    build: ./apps/publicProfile
    container_name: publicprofile
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy
    depends_on:
      - mongo
    ports:
      - "4001:4001"

  userprofile:
    build: ./apps/userProfile
    container_name: userprofile
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy
      - JWT_SECRET=super_secret_breezy
    depends_on:
      - mongo
    ports:
      - "4003:4003"
  
  useraccount:
    build: ./apps/userAccount
    container_name: useraccount
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy
    depends_on:
      - mongo
    ports:
      - "4004:4004"


  authentification:
    build: ./apps/authentification
    container_name: authentification
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy
      - JWT_SECRET=super_secret_breezy
    depends_on:
      - mongo
    ports:
      - "4005:4005"
  
  post:
    build: ./apps/post
    container_name: post
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy
    depends_on:
      - mongo
    ports:
      - "4006:4006"
  
  interaction:
    build: ./apps/interaction
    container_name: interaction
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy
    depends_on:
      - mongo
    ports:
      - "4007:4007"

  feed:
    build: ./apps/feed
    container_name: feed
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy
    depends_on:
      - mongo
    ports:
      - "4008:4008"

  nginx:
    image: nginx:alpine
    container_name: breezy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - followers
      - publicprofile
      - userprofile
      - useraccount
      - authentification
      - post

  gateway:
    build: ./apps/gateway
    container_name: gateway
    environment:
      - JWT_SECRET=super_secret_breezy
    ports:
      - "4000:4000"
    depends_on:
      - authentification
      - followers
      - publicprofile
      - userprofile
      - useraccount
      - post
      - interaction
      - feed

volumes:
  mongo-data: